# Generated by Django 6.0 on 2025-12-11 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
        ('core', '0020_remove_studentprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.volunteer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password must be at least 8 characters.', max_length=128, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
