# Generated by Django 6.0 on 2025-12-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerbackground',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteercontact',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteereducation',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteeraccount',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteeraddress',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteeraffiliation',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='VolunteerBackground',
        ),
        migrations.DeleteModel(
            name='VolunteerContact',
        ),
        migrations.DeleteModel(
            name='VolunteerEducation',
        ),
        migrations.DeleteModel(
            name='VolunteerAccount',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='VolunteerAddress',
        ),
        migrations.DeleteModel(
            name='VolunteerAffiliation',
        ),
    ]
