# Generated by Django 5.2.8 on 2025-11-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='college',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='degree_program',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='hobbies_interests',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='org_affiliation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year_graduated',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year_level',
        ),
        migrations.CreateModel(
            name='VolunteerAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAffiliation',
            fields=[
                ('volunteer_affiliation_id', models.AutoField(primary_key=True, serialize=False)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affiliation')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerBackground',
            fields=[
                ('background_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('org_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('hobbies_interests', models.TextField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=15)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerEducation',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_program', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_graduated', models.CharField(blank=True, max_length=4, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.volunteer')),
            ],
        ),
    ]
