# Generated by Django 5.2.8 on 2025-11-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_volunteer_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='affiliation',
            table='core_affiliation',
        ),
        migrations.AlterModelTable(
            name='emergencycontact',
            table='core_emergencycontact',
        ),
        migrations.AlterModelTable(
            name='programinterest',
            table='core_programinterest',
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table='core_volunteer',
        ),
        migrations.AlterModelTable(
            name='volunteeraccount',
            table='core_volunteeraccount',
        ),
        migrations.AlterModelTable(
            name='volunteeraddress',
            table='core_volunteeraddress',
        ),
        migrations.AlterModelTable(
            name='volunteeraffiliation',
            table='core_volunteeraffiliation',
        ),
        migrations.AlterModelTable(
            name='volunteerbackground',
            table='core_volunteerbackground',
        ),
        migrations.AlterModelTable(
            name='volunteercontact',
            table='core_volunteercontact',
        ),
        migrations.AlterModelTable(
            name='volunteereducation',
            table='core_volunteereducation',
        ),
    ]
