# Generated by Django 5.2.8 on 2025-11-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_affiliation_table_alter_emergencycontact_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='affiliation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emergencycontact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='programinterest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteeraccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteeraddress',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteeraffiliation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteerbackground',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteercontact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='volunteereducation',
            table=None,
        ),
    ]
