# Generated by Django 5.2.8 on 2025-11-25 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_affiliation_table_alter_emergencycontact_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeraffiliation',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='volunteeraffiliation',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteereducation',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='affiliation_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('alumni', 'Alumni'), ('staff', 'UP Staff'), ('faculty', 'Faculty'), ('retiree', 'Retiree')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituent_unit', models.CharField(max_length=100)),
                ('degree_program', models.CharField(max_length=100)),
                ('year_graduated', models.CharField(max_length=4)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='RetireeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_while_in_up', models.CharField(max_length=100)),
                ('office_college_department', models.CharField(max_length=255)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiree_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='core.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_program', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='core.volunteer')),
            ],
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='VolunteerAffiliation',
        ),
        migrations.DeleteModel(
            name='VolunteerEducation',
        ),
    ]
