# Generated by Django 5.2.8 on 2025-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_volunteeraffiliation_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='availability_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='status',
            field=models.CharField(choices=[('Joined', 'Joined'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Joined', max_length=20),
        ),
    ]
