# Generated by Django 5.2.8 on 2025-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_eventschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventschedule',
            options={},
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
