# Generated by Django 5.2.8 on 2025-12-02 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_eventschedule_options_alter_eventschedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admin'),
        ),
    ]
