# Generated by Django 5.2.8 on 2025-12-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_event_date_end_remove_event_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='time_end',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='time_start',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
    ]
