# Generated by Django 5.2.8 on 2025-12-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_date_end_event_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
