# Generated by Django 5.2.8 on 2025-12-07 11:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='max_slots',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='end_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VolunteerScheduleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='core.eventschedule')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.volunteer')),
            ],
        ),
    ]
