# Generated by Django 5.2.8 on 2025-12-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eventschedule_max_slots_alter_eventschedule_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
    ]
