# Generated by Django 6.0 on 2025-12-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_emergencycontact_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinterest',
            name='program_interest_id',
        ),
        migrations.AddField(
            model_name='programinterest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programinterest',
            name='program_name',
            field=models.CharField(max_length=100),
        ),
    ]
