# Generated by Django 6.0 on 2025-12-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_programinterest_program_interest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_status', models.CharField(blank=True, max_length=255, null=True)),
                ('tagapag_ugnay', models.CharField(blank=True, max_length=10, null=True)),
                ('other_organization', models.CharField(blank=True, max_length=10, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affirmative_action_subjects', models.JSONField(default=list)),
                ('how_did_you_hear', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='core.volunteer')),
            ],
        ),
    ]
