# Generated by Django 6.0 on 2025-12-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_volunteermeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
    ]
