# Generated by Django 6.0 on 2025-12-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_studentprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerbackground',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='volunteermeta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='volunteermeta',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='volunteermeta',
            name='affirmative_action_subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteermeta',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteermeta',
            name='other_organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteermeta',
            name='tagapag_ugnay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteermeta',
            name='volunteer_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
